configMapGenerator:
- files:
  - application.yml
  name: 82058454.test-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: cepgstapacr.azurecr.io/82058454.test
  newTag: "202408120727"
- name: cepgstapacr.azurecr.io/cloud-sample
  newTag: "202411220817"
